// import { searchMovies } from "../all_src/searchMovies.js";
// import { handleReview } from "../handleReview.js";
// import { toTheTop } from "../all_src/toTheTop.js";
// import { review } from "../review.js";
// import { detailInfo } from "./detailInfo.js";
// review();
// searchMovies();
// toTheTop();
// // handleReview();
// detailInfo();